Repository ProgrammingPhilippines/progphil-bot, pull requests merged in 2023-01, with the labels that each got.

#35 Media announce better method
  bot/cogs/announcements.py
  pyproject.toml
Labels: chore

#37 Multiline with media
  bot/cogs/announcements.py
  bot/utils/modals.py
Labels: feature

#40 Github Action Workflow
  .github/workflows/main.yml
Labels: enhancement

#42 Improve readme
  README.md
Labels: documentation, enhancement

#45 Test docker
  .dockerignore
  Dockerfile
Labels: enhancement, feature

#48 Working Docker CI patch
  .github/workflows/docker-ci.yml
Labels: bug, enhancement

#54 Error handling
  bot/cogs/announcements.py
  bot/cogs/error_handling.py
Labels: feature

#52 Readme badges
  .dockerignore
  README.md
Labels: documentation, chore

#58 added auto deployment
  .github/workflows/docker-ci.yml
Labels: enhancement

#59 Enhancement/cicd checking
  .github/workflows/docker-ci.yml
Labels: enhancement

#64 Fix: Added Auto release actions using release-please-actions
  .github/workflows/release.yml
Labels: enhancement, feature
